music-app/routes/web.php
<?php

use App\Http\Controllers\AlbumController;
use App\Http\Controllers\Customer\CoinController;
use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Customer\DownloadController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SingerController;
use App\Http\Controllers\SongController;
use App\Http\Controllers\Customer\SongController as SonggController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\CheckRole;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'music' ], function()
{
    Route::get('login',[LoginController::class,'showLoginForm'])->name('login');
    Route::post('login',[LoginController::class,'login']);
    Route::get('register',[LoginController::class,'showRegistrationForm'])->name('register');
    Route::post('register',[LoginController::class,'register']);
    Route::get('logout',[LoginController::class,'logout'])->name('logout');
});

Route::group(['middleware' => 'checkrole'],function () {
    Route::resource('/genre',GenreController::class);
    Route::resource('/singer',SingerController::class);
    Route::resource('/album',AlbumController::class);
    Route::resource('/song',SongController::class);
});

Route::post('/favorite/add/{song}',[ FavoriteController::class,'addFavorite'])->name('add');
Route::delete('/favorite/del/{song}',[ FavoriteController::class,'removeFavorite'])->name('del');
Route::get('/favorite/index',[ FavoriteController::class,'index'])->name('index');
Route::resource('/customer',SonggController::class);
Route::get('/home',[CustomerController::class, 'index'])->name('home');
Route::resource('/customer/coin',CoinController::class);
Route::resource('/user',UserController::class);
Route::resource('/coin',CoinController::class);
Route::post('/download', [DownloadController::class,'download'])->name('download');
Route::post('/user/addcoin/{id}', [UserController::class,'deposit'])->name('deposit');

music-app/app/Models/Song.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Song extends Model
{
    use HasFactory;

    protected $fillable =[ 'name', 'album_id', 'file', 'price' ];

    public function album()
    {
        // return $this->hasMany(Album::class,'album_id', 'id');
        return $this->belongsTo(Album::class,'album_id', 'id');
    }

    public function user(){
        return $this->belongsToMany(User::class,'favorites','song_id','user_id');
    }
}

music-app/app/Http/Controllers/Customer/SongController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Services\Customer\SongService;
use Illuminate\Http\Request;

class SongController extends Controller
{
    protected $songService;
    public function __construct(SongService $songService)
    {
        $this->songService = $songService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $songs = $this->songService->getAllSongs();

        $music =[];
        foreach($songs as $song){
            array_push($music,$song->file);
        }
        $title =[];
        foreach($songs as $song){
            array_push($title,$song->name);
        }
        return view('customer.music',['music' => $music, 'songs' => $songs, 'title' => $title]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

music-app/app/Http/Controllers/SongController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SongRequest;
use App\Services\AlbumService;
use App\Services\GenreService;
use App\Services\SingerService;
use App\Services\SongService;
use Exception;
use Illuminate\Http\Request;

class SongController extends Controller
{
    protected $songService;
    protected $albumService;
    protected $genreService;
    protected $singerService;

    public function __construct(SongService $songService, AlbumService $albumService, GenreService $genreService, SingerService $singerService)
    {
        $this->middleware('auth:web', ['except' => 'login']);
        $this->songService = $songService;
        $this->albumService = $albumService;
        $this->genreService = $genreService;
        $this->singerService = $singerService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $songs = $this->songService->getAllSongs();
            return view('songs.index', compact('songs'));
        } catch (Exception $exception) {
            return back()->withError($exception->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $songs = $this->songService->getAllSongs();
            $genres = $this->genreService->getAllGenres();
            $singers = $this->singerService->getAll();
            $albums = $this->albumService->getAllAlbums();
            return view('songs.create', compact('songs', 'genres', 'singers', 'albums'));
        } catch (Exception $exception) {
            return back()->withError($exception->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SongRequest $request)
    {
        try {
            $songData = $request->all();
            $song = $this->songService->createSong($songData);
            return redirect()->route('song.store')->with('success', 'Singer created successfully.');
        } catch (Exception $exception) {
            return back()->withError($exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($songId)
    {
        try {
            $albums = $this->albumService->getAllAlbums();
            $song = $this->songService->getSongById($songId);
            return view('songs.edit', compact('song', 'albums'));
        } catch (Exception $exception) {
            return back()->withError($exception->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SongRequest $request, $id)
    {
        try {
            $data = $request->all();
            $song = $this->songService->updateSong($id, $data);
            return redirect()->route('song.index')->with('success', 'Singer updated successfully.');
        } catch (Exception $exception) {
            return back()->withError($exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($songId)
    {
        try {
            $this->songService->deleteSong($songId);
            return redirect()->route('song.index')->with('success', 'Singer deleted successfully.');
        } catch (Exception $exception) {
            return back()->withError($exception->getMessage());
        }
    }
}

music-app/resources/views/songs/index.blade.php
{{-- <!DOCTYPE html>
<html lang="en">

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>

    <div class="container">
        <h2>Black/Dark Table</h2>
        <div class="pull-right mb-2">
            <a class="btn btn-success" href="{{ route('singer.create') }}"> Create Singer</a>
        </div>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Tên ca sĩ</th>
                    <th>Hình ảnh</th>
                    <th>Acion</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($singers as $key => $singer)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $singer->name }}</td>
                        <td>
                            <img style="width: 100px; height: 100px;" src="{{ asset('singers') }}/{{ $singer->image }}" alt="">
                        </td>
                        <td>
                            <a class="btn btn-primary" href="{{ route('singer.edit', $singer->id) }}">Edit</a>
                            <form method="post" action="{{ route('singer.destroy', $singer->id) }}">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger mt-3">Delete</button>
                            </form>
                        </td>


                    </tr>
                @endforeach

            </tbody>
        </table>
    </div>

</body>

</html> --}}



<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="keywords"
        content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Matrix lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Matrix admin lite design, Matrix admin lite dashboard bootstrap 5 dashboard template" />
    <meta name="description"
        content="Matrix Admin Lite Free Version is powerful and clean admin dashboard template, inpired from Bootstrap Framework" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Matrix Admin Lite Free Versions Template by WrapPixel</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png" />
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="../assets/extra-libs/multicheck/multicheck.css" />
    <link href="../assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="../dist/css/style.min.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
        data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- ============================================================== -->
                    <!-- Logo -->
                    <!-- ============================================================== -->
                    <a class="navbar-brand" href="index.html">
                        <!-- Logo icon -->
                        <b class="logo-icon ps-2">
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="../assets/images/logo-icon.png" alt="homepage" class="light-logo" width="25" />
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span class="logo-text ms-2">
                            <!-- dark Logo text -->
                            <img src="../assets/images/logo-text.png" alt="homepage" class="light-logo" />
                        </span>
                    </a>
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
                        <i class="ti-menu ti-close"></i></a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <ul class="navbar-nav float-start me-auto">
                        <li class="nav-item d-none d-lg-block">
                            <a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)"
                                data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="d-none d-md-block">Create New </span>
                                <span class="d-block d-md-none"><i class="fa fa-plus"></i></span>
                            </a>
                        </li>
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->
                        <li class="nav-item search-box">
                            <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i
                                    class="mdi mdi-magnify fs-4"></i></a>
                            <form class="app-search position-absolute">
                                <input type="text" class="form-control" placeholder="Search &amp; enter" />
                                <a class="srh-btn"><i class="mdi mdi-window-close"></i></a>
                            </form>
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- Right side toggle and nav items -->
                    <!-- ============================================================== -->
                    @include('navbar')
                </div>
            </nav>
        </header>
        @include('aside')
        <div class="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Danh sách bài hát</h5>
                                <div class="pull-right mb-2">
                                    <a class="btn btn-success" href="{{ route('song.create') }}"> Create Song</a>
                                </div>
                                <div class="table-responsive">
                                    <table id="zero_config" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                            <tr>
                                                <th>#</th>
                                                <th>Tên bài hát</th>
                                                <th>Tên ca sĩ</th>
                                                <th>Thể loại</th>
                                                <th>Album</th>
                                                <th>Bài hát</th>
                                                <th>Giá</th>
                                                <th>Acion</th>
                                            </tr>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($songs as $key => $song)
                                                <tr>
                                                    <td>{{ $key + 1 }}</td>
                                                    <td>{{ $song->name }}</td>
                                                    <td>{{ $song->album->singer->name }}</td>
                                                    <td>{{ $song->album->genre->name }}</td>
                                                    <td>{{ $song->album->name }}</td>
                                                    <td>
                                                        <audio controls>
                                                            <source src="{{ asset('singers/' . $song->file) }}" type="audio/mpeg">
                                                        </audio>
                                                    </td>
                                                    <td>{{ $song->price }}</td>
                                                    <td>
                                                        <a class="btn btn-primary"
                                                            href="{{ route('song.edit', $song->id) }}">Edit</a>
                                                        <form method="post"
                                                            action="{{ route('song.destroy', $song->id) }}">
                                                            @csrf
                                                            @method('DELETE')

                                                            <button type="submit" onclick="return(confirm('Bạn có muốn xóa?'))"
                                                                class="btn btn-danger mt-3">Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>#</th>
                                                <th>Tên bài hát</th>
                                                <th>Tên ca sĩ</th>
                                                <th>Thể loại</th>
                                                <th>Album</th>
                                                <th>Bài hát</th>
                                                <th>Giá</th>
                                                <th>Acion</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="../assets/libs/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="../assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="../assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="../assets/extra-libs/sparkline/sparkline.js"></script>
    <!--Wave Effects -->
    <script src="../dist/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="../dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="../dist/js/custom.min.js"></script>
    <!-- this page js -->
    <script src="../assets/extra-libs/multicheck/datatable-checkbox-init.js"></script>
    <script src="../assets/extra-libs/multicheck/jquery.multicheck.js"></script>
    <script src="../assets/extra-libs/DataTables/datatables.min.js"></script>
    <script>
        /****************************************
         *       Basic Table                   *
         ****************************************/
        $("#zero_config").DataTable();
    </script>
</body>

</html>